### ISSUE TITLE
Implement override genesis function

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet-sdk#104]
Currently, the project lacks an override genesis function, which is essential for accommodating the forthcoming chain specification. This function should facilitate key patching to override existing keys without generating non-existent ones. Implementing this feature is crucial to maintain compatibility and ensure smooth integration with the provided chain specification.
The keys patched should override the existing one but not create non-existant ones;

**Comment by pepoviola** [comment]
Implemented in https://github.com/paritytech/zombienet-sdk/pull/111.
