### ISSUE TITLE
[ci] Add spell check action

### ISSUE THREAD

**Issue by pepoviola** [paritytech/zombienet-sdk#149]
We should catch this typos as part of our ci/actions (e.g https://github.com/paritytech/zombienet-sdk/pull/148).

**Comment by TomaszWaszczyk** [comment]
@pepoviola I want to solve the issue. Addition of [cargo-spellcheck](https://github.com/drahnr/cargo-spellcheck) is a proper way to finish the issue?

**Comment by pepoviola** [comment]
Hi @TomaszWaszczyk, yes. Use `cargo-spellcheck` sounds good 👍 .

Thx!

**Comment by TomaszWaszczyk** [comment]
@pepoviola I think you can close the issue ;-)

**Comment by pepoviola** [comment]
Thanks @TomaszWaszczyk 🙌
