### ISSUE TITLE
Ability to test against bad network conditions

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet-sdk#15]
**In the future, it would be nice for zombienet to provide an API for injecting network issues.** 

Zombienet clusters and internal testnets are usually spawned within a single data center, where network speeds are often close to optimal. Unfortunately, in the real world things are not so ideal. Therefore, I'd propose to extend zombienet functionality w/ ability to simulate bad & adversary network conditions. Sort of how [Jepsen](https://jepsen.io/) provides an [API for splitting the network into halves (or majorities)](https://jepsen-io.github.io/jepsen/jepsen.nemesis.html#var-partition-halves). 

Here is the list of things I think we want in the first approximation:

1. introduce latency, packet loss & jitter (`tc & netem` on Linux) for all connections of the given peer
2. isolate the single peer from the rest of the network for the given period (`iptables` on Linux)
3. partition the network into two groups (halves, majority & minority) (`iptables` on Linux)

(1) can be simplified into multiple predefined options: "slow", "50_loss", etc.

_Slightly unrelated, but killing random nodes (chaos engineering; using tools like https://github.com/asobti/kube-monkey) also sound like a good idea to me._

Curious to hear your thoughts on this 🙏

How hard would it be to implement something like this? Are there existing tools for Kubernetes that give you control over network? What zombienet API would look like?

---- 
UPDATE:

Adding individual issues to track progress:

- [x] #16
- [x] #18
- [x] #17

**Comment by melekes** [comment]
cc @melekes (tagging myself so I don't loose this issue)
