### ISSUE TITLE
Error when parsing empty args array

### ISSUE THREAD

**Issue by AlexD10S** [paritytech/zombienet-sdk#202]
I am not sure if this is an issue with the SDK or is something that shouldn't be in the Config file. 

When I try to parse a Config file that contains an empty array for args: `args = [""]`, it throws an error (The config file is the one in the [frontier-parachain-template](https://github.com/paritytech/frontier-parachain-template)):
```
TOML parse error at line 30, column 11
   |
30 |   args = [""]
   |           ^^
the provided argument is invalid and doesn't match Arg::Option or Arg::Flag
```

After some researching I can see the error is when parsing the Config file in the function load_from_toml ([line](https://github.com/paritytech/zombienet-sdk/blob/main/crates/configuration/src/network.rs#L75)):
```rs
let mut network_config: NetworkConfig = toml::from_str(
            re.replace_all(&file_str, "$field_name = \"$u128_value\"")
                .as_ref(),
        )?;
```
Should be ignored if the array is empty?

Thanks for this amazing SDK!! We are using it in our tool [pop-cli](https://github.com/r0gue-io/pop-cli).

**Comment by pepoviola** [comment]
Hi @AlexD10S, thanks for your feedback! I will update the `toml` in that repo since an empty string can not be deserialized to a valid argument (and I'm not sure if we want to deserialize to an empty arg). That make sense to you? 

Thanks again for your feedback :)

**Comment by AlexD10S** [comment]
It makes sense, thanks @pepoviola
