### ISSUE TITLE
Orchestrator Crate

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet-sdk#26]
Responsible for bringing the state of the running network to the expected configuration and managing it in real-time (`./crates/orchestrator`)
_Note_: Depends on [`Support`](#23 ), [`Configuration`](#24 ), [`Provider`](#25 ) crates;
- [x] #40
- [x] #41
- [x] #42
- [x] #43

**Comment by pepoviola** [comment]
Done as part of https://github.com/paritytech/zombienet-sdk/pull/101
