### ISSUE TITLE
Validation of configuration

### ISSUE THREAD

**Issue by l0r1s** [paritytech/zombienet-sdk#64]
Following the work done on https://github.com/paritytech/zombienet-sdk/pull/51 the validation of the configuration has been split apart to make validation easier

- [x] Add validation
- - [x] Node
- - [x] Relaychain
- - [x] Parachain 
- - [x] HRMP channels
- - [x] Network

- [x] Add test for validation
- - [x] Node
- - [x] Relaychain
- - [x] Parachain 
- - [x] HRMP channels
- - [x] Network

**Comment by pepoviola** [comment]
Sounds good, I think at this stage we should only validate that the values make sense. For example, 
- `default_command` / `string` : the string can't contains `spaces`
- `default_image` / `image` : we can use the same `regex` that we use in the current version
- `MultiAddress` : we can add a regex validation or check if we can add a crate to validate it
- `AssetLocation`: regex to validate valid `url` / `os path`
- `ResourceQuantity` : regex
- `chain`: check that doesn't contains spaces

**Comment by l0r1s** [comment]
Alright, thanks, working on it !

**Comment by l0r1s** [comment]
Done in https://github.com/paritytech/zombienet-sdk/pull/71
